import {readFileSync, writeFileSync} from 'node:fs';
const profile = JSON.parse(readFileSync(new URL('./profile.json', import.meta.url), 'utf8'));
const esc = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const external = (url, label, cls = '') => `<a class="${cls}" href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(label)}</a>`;
const papers = [...profile.publications].sort((a,b) => b.year-a.year);
function paperCard(p) {
  return `<article class="paper"><div class="paper-badge"><span>${esc(p.method)}</span><small>TGRS · ${p.year}</small></div><div class="paper-content"><h3>${external(p.paper,p.title)}</h3><p class="authors">${p.authors.map(a => a===profile.name ? `<strong>${esc(a)}</strong>` : esc(a)).join(', ')}</p><p class="venue"><em>${esc(p.venue)}</em>, ${p.year} · Vol. ${esc(p.volume)}, pp. ${esc(p.pages)}</p><p class="summary">${esc(p.summary)}</p><div class="paper-links">${external(p.paper,'Paper ↗')}${external(p.code,'Code ↗')}${p.doi ? external('https://doi.org/'+p.doi,'DOI ↗') : ''}</div></div></article>`;
}
const sidebar = `<aside class="profile card"><div class="portrait">${profile.portrait ? `<img src="${esc(profile.portrait)}" alt="${esc(profile.name)}">` : '<span aria-hidden="true">HP</span>'}</div><h1>${esc(profile.name)}</h1><p class="affiliation">${esc(profile.affiliation)}</p><p class="location">${esc(profile.affiliationShort)}</p><div class="social">${external('https://github.com/'+profile.github,'GitHub ↗')}${profile.email ? `<a href="mailto:${esc(profile.email)}">Email ↗</a>` : ''}${profile.scholar ? external(profile.scholar,'Google Scholar ↗') : ''}</div><div class="profile-note">Remote sensing · Image restoration</div></aside>`;
const home = `<section class="card about"><div class="eyebrow">ACADEMIC HOMEPAGE</div><h2>About Me</h2><p>${esc(profile.bio)}</p><h3 class="interest-heading">Research interests</h3><div class="tags">${profile.interests.map(i => `<span>${esc(i)}</span>`).join('')}</div></section><section class="card publications"><div class="section-header"><h2>Selected Publications</h2><a href="publications.html">View all →</a></div>${papers.map(paperCard).join('')}</section><section class="card code-note"><h2>Research Code</h2><p>Explore the implementations accompanying my publications.</p><a href="projects.html">Browse projects →</a></section>`;
const publications = `<section class="card page-intro"><div class="eyebrow">RESEARCH</div><h2>Publications</h2><p>Published work on remote sensing image restoration.</p></section>${[...new Set(papers.map(p=>p.year))].map(year => `<section class="card publications"><div class="section-header"><h2>${year}</h2><span class="muted">IEEE TGRS</span></div>${papers.filter(p=>p.year===year).map(paperCard).join('')}</section>`).join('')}`;
const projects = `<section class="card page-intro"><div class="eyebrow">OPEN SOURCE</div><h2>Research Code</h2><p>Code repositories associated with my publications.</p></section>${papers.map(p=>`<article class="card project"><div class="eyebrow">${p.year} · PYTHON / MATLAB</div><h2>${esc(p.method)}</h2><p>${esc(p.summary)}</p><div class="paper-links">${external(p.code,'View repository ↗')}${external(p.paper,'Related paper ↗')}</div></article>`).join('')}`;
function page(title, active, content) {
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} | ${esc(profile.name)}</title><meta name="description" content="${esc(profile.bio)}"><meta property="og:title" content="${esc(profile.name)} — Academic Homepage"><meta property="og:description" content="Remote sensing image restoration, low-rank tensor modeling, and deep learning."><meta property="og:type" content="website"><link rel="icon" href="favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="styles.css"></head>
<body><a class="skip-link" href="#main">Skip to content</a><header class="navbar"><nav class="nav-container" aria-label="Main navigation"><a class="brand" href="index.html">${esc(profile.name)}</a><button class="menu-toggle" type="button" aria-controls="nav-links" aria-expanded="false">Menu ☰</button><div class="nav-links" id="nav-links">${[['Home','index.html'],['Publications','publications.html'],['Research Code','projects.html']].map(([name,url])=>`<a href="${url}"${name===active ? ' class="active" aria-current="page"' : ''}>${name}</a>`).join('')}</div></nav></header><main class="layout" id="main">${sidebar}<div class="content">${content}</div></main><footer><span>© ${esc(profile.name)}</span><span>Adapted from ${external('https://github.com/luost26/academic-homepage','academic-homepage')} · Hosted on GitHub Pages</span></footer><script src="site.js"></script></body></html>`;
}
for (const [file,title,active,content] of [['index.html','Academic Homepage','Home',home],['publications.html','Publications','Publications',publications],['projects.html','Research Code','Research Code',projects]]) {
  writeFileSync(new URL(file, import.meta.url),page(title,active,content));
}
console.log('Built homepage, publications, and research code pages.');
